name: Build VS Code Extension

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "editors/vscode/**"
      - "tools/**"

jobs:
  build:
    if: github.base_ref == github.event.repository.default_branch
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: editors/vscode
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install vsce
        run: npm install --global @vscode/vsce

      - name: Install extension dependencies
        run: npm ci

      - name: Build extension bundle
        run: npm run build

      - name: Run extension tests
        run: npm run test

      - name: Check production dependency tree
        run: npm list --production --depth=99999 --loglevel=error

      - name: Package extension
        run: vsce package
